// src/routes/lesson/+page.svelte
<script lang="ts">
import { goto } from '$app/navigation';

type Phase = 'setup' | 'read' | 'decide' | 'reveal';
type Choice = 'fold' | 'call' | 'raise' | null;

let phase = $state<Phase>('setup');
let confidence = $state(60);
let choice = $state<Choice>(null);
let tellMeter = $state(0);
let handNumber = $state(1);
let totalHands = 5;
let xpEarned = $state(0);

const correct = $derived(choice === 'raise');

const phaseText = $derived.by(() => {
	switch (phase) {
		case 'setup':
			return 'Folded to you on the button.';
		case 'read':
			return 'Villain just min-raised. Quickly.';
		case 'decide':
			return "What's your move?";
		case 'reveal':
			return correct ? 'Nice read.' : 'Hmm. Re-deal that one.';
	}
});

const xpResult = $derived.by(() => {
	if (phase !== 'reveal' || !choice) return 0;
	const base = confidence > 0 ? confidence : 1;
	if (correct) return Math.round((20 * base) / 60);
	return -Math.round((5 * base) / 60);
});

$effect(() => {
	if (phase !== 'read') return;
	let v = 0;
	const id = setInterval(() => {
		v = Math.min(100, v + 4);
		tellMeter = v;
		if (v >= 100) clearInterval(id);
	}, 60);
	return () => clearInterval(id);
});

$effect(() => {
	if (phase === 'setup') {
		const t = setTimeout(() => {
			phase = 'read';
		}, 1400);
		return () => clearTimeout(t);
	}
});

function choose(c: Choice) {
	choice = c;
	phase = 'reveal';
	xpEarned += xpResult;
}

function nextHand() {
	if (handNumber >= totalHands) {
		goto('/home');
		return;
	}
	handNumber += 1;
	phase = 'setup';
	choice = null;
	tellMeter = 0;
	confidence = 60;
}
</script>

<div class="screen felt-bg">
	<TopBar onBack={() => goto('/home')}>
		{#snippet center()}
			Hand {handNumber} of {totalHands}
		{/snippet}
		{#snippet right()}
			<Pill><span style="color: var(--gold);">●</span> {xpEarned >= 0 ? `+${xpEarned}` : xpEarned} XP</Pill>
		{/snippet}
	</TopBar>

	<div class="scenario">
		<div class="eyebrow" style="color: var(--gold);">UTG · 100BB · $1/$2 NLHE</div>
		<div class="serif scenario-text">
			{phaseText}
		</div>
	</div>

	<div class="table-felt">
		<div class="opponent-zone">
			<div class="opponent-avatar">🎩</div>
			<div class="mono opponent-label">Villain · UTG</div>
			{#if phase === 'read' || phase === 'decide'}
				<div class="tell-meter">
					<span style="font-size: 10px;">👁</span>
					<div class="tell-track">
						<div class="tell-fill" style="width: {tellMeter}%;"></div>
					</div>
					<span class="mono tell-label">TELL</span>
				</div>
			{/if}
		</div>

		<div class="opponent-cards">
			<PlayingCard faceDown size="sm" treatment="classic" />
			<PlayingCard faceDown size="sm" treatment="classic" delay={80} />
		</div>

		<div class="pot-zone">
			<div class="eyebrow">Pot</div>
			<div class="mono pot-amount">$7</div>
			<div class="pot-chips">
				<Chip label="$1" class="chip-sm" />
				<Chip label="$2" class="chip-sm" />
			</div>
		</div>

		<div class="hero-cards">
			<PlayingCard rank="A" suit="♠" size="lg" treatment="classic" />
			<PlayingCard rank="K" suit="♠" size="lg" treatment="classic" delay={120} />
		</div>
	</div>

	<div class="decision-panel">
		{#if phase === 'read'}
			<div class="anim-float read-panel">
				<div class="eyebrow">Reading...</div>
				<div class="read-hint">
					Quick min-raise after a long pause = uncertainty.<br />
					Often a hand he wishes was bigger.
				</div>
				<button class="btn btn-primary" style="width: 100%; margin-top: 14px;" onclick={() => { phase = 'decide'; }}>
					Got it →
				</button>
			</div>
		{/if}

		{#if phase === 'decide'}
			<div class="anim-float">
				<div class="confidence-section">
					<div class="confidence-header">
						<span class="eyebrow">Confidence</span>
						<span class="mono confidence-value">{confidence}%</span>
					</div>
					<input
						type="range"
						min="20"
						max="100"
						bind:value={confidence}
						class="confidence-slider"
					/>
					<div class="confidence-hint">
						Right + bold = bigger XP. Wrong + bold = bigger lesson.
					</div>
				</div>

				<div class="action-grid">
					<button class="action-btn action-fold" onclick={() => choose('fold')}>
						<div class="action-icon">🗑️</div>
						<div class="action-label">Fold</div>
					</button>
					<button class="action-btn action-call" onclick={() => choose('call')}>
						<div class="action-icon">➡️</div>
						<div class="action-label">Call $4</div>
					</button>
					<button class="action-btn action-raise" onclick={() => choose('raise')}>
						<div class="action-icon">🔥</div>
						<div class="action-label">3-bet $14</div>
					</button>
				</div>
			</div>
		{/if}

		{#if phase === 'reveal'}
			<div class="anim-float reveal-panel" class:reveal-correct={correct} class:reveal-wrong={!correct}>
				<div class="reveal-header">
					<div class="eyebrow reveal-verdict">
						{correct ? '✓ Correct' : '✗ Not quite'}
					</div>
					<div class="mono reveal-xp">
						{correct ? `+${xpResult}` : xpResult} XP
					</div>
				</div>
				<div class="reveal-explanation">
					AKs vs an UTG min-raiser is a <em class="serif" style="color: var(--coral-soft);">premium 3-bet</em>.
					You either fold out his marginal stuff or build a pot you'll often win.
				</div>
				<button class="btn btn-cream" style="width: 100%; margin-top: 14px;" onclick={nextHand}>
					{handNumber >= totalHands ? 'Finish session' : 'Next hand →'}
				</button>
			</div>
		{/if}
	</div>
</div>

<style>
	.screen {
		display: flex;
		flex-direction: column;
		min-height: 100vh;
		background: var(--felt);
	}

	.scenario {
		padding: 4px 24px 0;
	}

	.scenario-text {
		font-size: 26px;
		line-height: 1.1;
		margin-top: 6px;
	}

	.table-felt {
		flex: 1;
		position: relative;
		margin: 20px 16px 0;
		border-radius: 32px;
		background: radial-gradient(ellipse at center, var(--felt-3) 0%, var(--felt) 70%);
		border: 1px solid var(--hairline-strong);
		box-shadow: inset 0 0 60px rgba(0,0,0,0.4);
		overflow: hidden;
	}

	.opponent-zone {
		position: absolute;
		top: 24px;
		left: 0;
		right: 0;
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	.opponent-avatar {
		width: 56px;
		height: 56px;
		border-radius: 999px;
		background: #2a1a14;
		border: 2px solid var(--hairline-strong);
		display: flex;
		align-items: center;
		justify-content: center;
		font-size: 22px;
	}

	.opponent-label {
		font-size: 11px;
		margin-top: 6px;
		color: var(--cream-dim);
		text-transform: uppercase;
		letter-spacing: 0.1em;
	}

	.tell-meter {
		margin-top: 10px;
		padding: 6px 12px;
		background: rgba(0,0,0,0.5);
		border-radius: 999px;
		display: flex;
		align-items: center;
		gap: 8px;
		border: 1px solid rgba(255,91,72,0.3);
	}

	.tell-track {
		width: 80px;
		height: 4px;
		border-radius: 2px;
		background: rgba(245,233,212,0.15);
		overflow: hidden;
	}

	.tell-fill {
		height: 100%;
		background: linear-gradient(90deg, var(--gold), var(--coral));
		transition: width 100ms linear;
	}

	.tell-label {
		font-size: 10px;
		color: var(--gold);
	}

	.opponent-cards {
		position: absolute;
		top: 100px;
		left: 50%;
		transform: translateX(-50%);
		display: flex;
		gap: 4px;
	}

	.pot-zone {
		position: absolute;
		top: 46%;
		left: 0;
		right: 0;
		text-align: center;
	}

	.pot-amount {
		font-size: 22px;
		font-weight: 700;
		color: var(--gold);
	}

	.pot-chips {
		display: inline-flex;
		gap: 2px;
		margin-top: 4px;
	}

	.chip-sm :global(.chip) {
		width: 22px;
		height: 22px;
		font-size: 9px;
	}

	.hero-cards {
		position: absolute;
		bottom: 24px;
		left: 50%;
		transform: translateX(-50%);
		display: flex;
		gap: 6px;
	}

	.decision-panel {
		padding: 20px 20px 28px;
	}

	.read-panel {
		text-align: center;
		padding: 12px;
	}

	.read-hint {
		font-size: 14px;
		color: var(--cream-dim);
		margin-top: 6px;
	}

	.confidence-section {
		padding: 0 4px 16px;
	}

	.confidence-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 8px;
	}

	.confidence-value {
		font-size: 12px;
		font-weight: 700;
		color: var(--coral);
	}

	.confidence-slider {
		width: 100%;
		accent-color: var(--coral);
	}

	.confidence-hint {
		font-size: 11px;
		color: var(--cream-dim);
		text-align: center;
		margin-top: 4px;
	}

	.action-grid {
		display: grid;
		grid-template-columns: 1fr 1fr 1fr;
		gap: 8px;
	}

	.action-btn {
		border-radius: 14px;
		padding: 14px 8px;
		cursor: pointer;
		font-family: inherit;
		border: 1.5px solid var(--hairline-strong);
	}

	.action-btn:active {
		opacity: 0.85;
		transform: translateY(1px);
	}

	.action-fold {
		background: rgba(245,233,212,0.06);
		color: var(--cream);
	}

	.action-call {
		background: rgba(233,185,73,0.1);
		color: var(--gold-soft);
		border-color: rgba(233,185,73,0.4);
	}

	.action-raise {
		background: var(--coral);
		color: #2a0a05;
		border-color: var(--coral);
		box-shadow: 0 4px 0 #b03d30;
	}

	.action-icon {
		font-size: 18px;
		margin-bottom: 4px;
	}

	.action-label {
		font-size: 13px;
		font-weight: 600;
	}

	.reveal-panel {
		border-radius: 18px;
		padding: 18px;
	}

	.reveal-correct {
		background: rgba(72,200,120,0.12);
		border: 1px solid rgba(72,200,120,0.4);
	}

	.reveal-wrong {
		background: rgba(255,91,72,0.12);
		border: 1px solid rgba(255,91,72,0.4);
	}

	.reveal-header {
		display: flex;
		justify-content: space-between;
		align-items: baseline;
		margin-bottom: 8px;
	}

	.reveal-verdict {
		color: #7adb9c;
	}

	.reveal-wrong .reveal-verdict {
		color: var(--coral-soft);
	}

	.reveal-xp {
		font-size: 14px;
		font-weight: 700;
		color: #7adb9c;
	}

	.reveal-wrong .reveal-xp {
		color: var(--coral-soft);
	}

	.reveal-explanation {
		font-size: 14px;
		line-height: 1.4;
	}

	.anim-float {
		animation: float-up 400ms ease both;
	}

	@keyframes float-up {
		from {
			opacity: 0;
			transform: translateY(16px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}
</style>

// Design/screens/lesson.jsx
/* global React */
function LessonScreen({ onComplete, onBack, tweaks }) {
  const [phase, setPhase] = React.useState('setup'); // setup -> read -> decide -> reveal
  const [confidence, setConfidence] = React.useState(60);
  const [choice, setChoice] = React.useState(null);
  const [tellMeter, setTellMeter] = React.useState(0);

  // animate tell meter during read phase
  React.useEffect(() => {
    if (phase !== 'read') return;
    let v = 0;
    const id = setInterval(() => {
      v = Math.min(100, v + 4);
      setTellMeter(v);
      if (v >= 100) clearInterval(id);
    }, 60);
    return () => clearInterval(id);
  }, [phase]);

  React.useEffect(() => {
    if (phase === 'setup') {
      const t = setTimeout(() => setPhase('read'), 1400);
      return () => clearTimeout(t);
    }
  }, [phase]);

  const choose = (c) => { setChoice(c); setPhase('reveal'); };
  const correct = choice === 'raise';

  return (
    <div className="screen felt-bg" style={{ background: 'var(--felt)' }}>
      <TopBar
        onBack={onBack}
        center="Hand 3 of 5"
        right={<div className="pill"><span style={{color:'var(--gold)'}}>●</span> +20 XP</div>}
      />

      {/* Scenario context */}
      <div style={{ padding: '4px 24px 0' }}>
        <div className="eyebrow" style={{ color: 'var(--gold)' }}>UTG · 100BB · $1/$2 NLHE</div>
        <div className="serif" style={{ fontSize: 26, lineHeight: 1.1, marginTop: 6 }}>
          {phase === 'setup' && 'Folded to you on the button.'}
          {phase === 'read' && 'Villain just min-raised. Quickly.'}
          {phase === 'decide' && 'What\'s your move?'}
          {phase === 'reveal' && (correct ? 'Nice read.' : <>Hmm. <em style={{color:'var(--coral-soft)'}}>Re-deal that one.</em></>)}
        </div>
      </div>

      {/* Table felt */}
      <div style={{ flex: 1, position: 'relative', margin: '20px 16px 0', borderRadius: 32, background: 'radial-gradient(ellipse at center, var(--felt-3) 0%, var(--felt) 70%)', border: '1px solid var(--hairline-strong)', boxShadow: 'inset 0 0 60px rgba(0,0,0,0.4)', overflow: 'hidden' }}>
        {/* opponent zone */}
        <div style={{ position: 'absolute', top: 24, left: 0, right: 0, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <div style={{ width: 56, height: 56, borderRadius: 999, background: '#2a1a14', border: '2px solid var(--hairline-strong)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22 }}>🎩</div>
          <div className="mono" style={{ fontSize: 11, marginTop: 6, color: 'var(--cream-dim)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Villain · UTG</div>
          {/* Tell meter — novel */}
          {(phase === 'read' || phase === 'decide') && (
            <div style={{ marginTop: 10, padding: '6px 12px', background: 'rgba(0,0,0,0.5)', borderRadius: 999, display: 'flex', alignItems: 'center', gap: 8, border: '1px solid rgba(255,91,72,0.3)' }}>
              <span style={{ fontSize: 10 }}>👁</span>
              <div style={{ width: 80, height: 4, borderRadius: 2, background: 'rgba(245,233,212,0.15)', overflow: 'hidden' }}>
                <div style={{ width: `${tellMeter}%`, height: '100%', background: 'linear-gradient(90deg, var(--gold), var(--coral))', transition: 'width 100ms linear' }} />
              </div>
              <span className="mono" style={{ fontSize: 10, color: 'var(--gold)' }}>TELL</span>
            </div>
          )}
        </div>

        {/* opponent cards face down */}
        <div style={{ position: 'absolute', top: 100, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 4 }}>
          <PlayingCard faceDown size="sm" treatment={tweaks.cardStyle} />
          <PlayingCard faceDown size="sm" treatment={tweaks.cardStyle} delay={80} />
        </div>

        {/* pot */}
        <div style={{ position: 'absolute', top: '46%', left: 0, right: 0, textAlign: 'center' }}>
          <div className="eyebrow">Pot</div>
          <div className="mono" style={{ fontSize: 22, fontWeight: 700, color: 'var(--gold)' }}>$7</div>
          <div style={{ display: 'inline-flex', gap: 2, marginTop: 4 }}>
            <span className="chip" style={{ width: 22, height: 22, fontSize: 9 }}>$1</span>
            <span className="chip" style={{ width: 22, height: 22, fontSize: 9 }}>$2</span>
          </div>
        </div>

        {/* hero cards */}
        <div style={{ position: 'absolute', bottom: 24, left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: 6 }}>
          <PlayingCard rank="A" suit="♠" size="lg" treatment={tweaks.cardStyle} />
          <PlayingCard rank="K" suit="♠" size="lg" treatment={tweaks.cardStyle} delay={120} />
        </div>
      </div>

      {/* Decision panel */}
      <div style={{ padding: '20px 20px 28px' }}>
        {phase === 'read' && (
          <div className="anim-float" style={{ textAlign: 'center', padding: 12 }}>
            <div className="eyebrow">Reading...</div>
            <div style={{ fontSize: 14, color: 'var(--cream-dim)', marginTop: 6 }}>Quick min-raise after a long pause = uncertainty.<br/>Often a hand he wishes was bigger.</div>
            <button className="btn btn-primary" style={{ width: '100%', marginTop: 14 }} onClick={() => setPhase('decide')}>
              Got it →
            </button>
          </div>
        )}

        {phase === 'decide' && (
          <div className="anim-float">
            {/* Confidence slider — novel */}
            <div style={{ padding: '0 4px 16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                <span className="eyebrow">Confidence</span>
                <span className="mono" style={{ fontSize: 12, fontWeight: 700, color: 'var(--coral)' }}>{confidence}%</span>
              </div>
              <input type="range" min="20" max="100" value={confidence} onChange={e => setConfidence(+e.target.value)}
                style={{ width: '100%', accentColor: 'var(--coral)' }} />
              <div style={{ fontSize: 11, color: 'var(--cream-dim)', textAlign: 'center', marginTop: 4 }}>
                Right + bold = bigger XP. Wrong + bold = bigger lesson.
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
              <button onClick={() => choose('fold')} style={{ background: 'rgba(245,233,212,0.06)', border: '1.5px solid var(--hairline-strong)', borderRadius: 14, padding: '14px 8px', color: 'var(--cream)', cursor: 'pointer', fontFamily: 'inherit' }}>
                <div style={{ fontSize: 18, marginBottom: 4 }}>🗑️</div>
                <div style={{ fontSize: 13, fontWeight: 600 }}>Fold</div>
              </button>
              <button onClick={() => choose('call')} style={{ background: 'rgba(233,185,73,0.1)', border: '1.5px solid rgba(233,185,73,0.4)', borderRadius: 14, padding: '14px 8px', color: 'var(--gold-soft)', cursor: 'pointer', fontFamily: 'inherit' }}>
                <div style={{ fontSize: 18, marginBottom: 4 }}>➡️</div>
                <div style={{ fontSize: 13, fontWeight: 600 }}>Call $4</div>
              </button>
              <button onClick={() => choose('raise')} style={{ background: 'var(--coral)', border: '1.5px solid var(--coral)', borderRadius: 14, padding: '14px 8px', color: '#2a0a05', cursor: 'pointer', fontFamily: 'inherit', boxShadow: '0 4px 0 #b03d30' }}>
                <div style={{ fontSize: 18, marginBottom: 4 }}>🔥</div>
                <div style={{ fontSize: 13, fontWeight: 700 }}>3-bet $14</div>
              </button>
            </div>
          </div>
        )}

        {phase === 'reveal' && (
          <div className="anim-float" style={{ borderRadius: 18, padding: 18, background: correct ? 'rgba(72,200,120,0.12)' : 'rgba(255,91,72,0.12)', border: `1px solid ${correct ? 'rgba(72,200,120,0.4)' : 'rgba(255,91,72,0.4)'}` }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 8 }}>
              <div className="eyebrow" style={{ color: correct ? '#7adb9c' : 'var(--coral-soft)' }}>{correct ? '✓ Correct' : '✗ Not quite'}</div>
              <div className="mono" style={{ fontSize: 14, fontWeight: 700, color: correct ? '#7adb9c' : 'var(--coral-soft)' }}>{correct ? `+${Math.round(20 * confidence/60)} XP` : `-${Math.round(5 * confidence/60)} XP`}</div>
            </div>
            <div style={{ fontSize: 14, lineHeight: 1.4 }}>
              AKs vs an UTG min-raiser is a <em className="serif" style={{color:'var(--coral-soft)'}}>premium 3-bet</em>. You either fold out his marginal stuff or build a pot you'll often win.
            </div>
            <button className="btn btn-cream" style={{ width: '100%', marginTop: 14 }} onClick={onComplete}>
              Next hand →
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

window.LessonScreen = LessonScreen;
